apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 5 
  strategy: {}
  template:
    spec:
      containers:
      - image: instavote/vote:fixed
        name: vote
